### ISSUE TITLE
sign in is not working 

### ISSUE THREAD

**Issue by Nareshallu** [kishorebqsp/samplw#6] opened 2019-08-01 06:51 UTC
sign in is not working 
![14-6-19](https://user-images.githubusercontent.com/53554454/62271524-797e0580-b456-11e9-8447-87a848dd9180.png)

**Comment by Nareshallu** [comment] 2019-08-01 06:53
tfgyuyhguh
![10-6-19 2](https://user-images.githubusercontent.com/53554454/62271807-235d9200-b457-11e9-9e7d-b33eb4d31c24.png)
defect video URL(https://github.com/kishorebqsp/samplw/issues/6)

**Comment by Nareshallu** [comment] 2019-08-01 06:54
https://prnt.sc/nl1d3w
--


![10-9-19](https://user-images.githubusercontent.com/53554454/62271877-5acc3e80-b457-11e9-96a2-a8271997b095.png)

**Comment by kishorebqsp** [comment] 2019-08-01 07:08
bug
Duplicate of #

**Closed as completed by kishorebqsp** 2019-08-01 07:08 UTC
Labels: bug
